# Generated by Django 5.2.8 on 2025-11-29 11:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Podaj nazwę ćwiczenia, np. "Wyciskanie leżąc", "Przysiad".', max_length=100, verbose_name='Nazwa ćwiczenia')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Wybierz dzień i godzinę rozpoczęcia sesji.', verbose_name='Początek treningu')),
                ('end', models.DateTimeField(help_text='Wybierz dzień i godzinę zakończenia sesji.', verbose_name='Koniec treningu')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0, help_text='Użyty ciężar w kilogramach. Dla ćwiczeń bez obciążenia wpisz 0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Ciężar (kg)')),
                ('sets', models.PositiveIntegerField(help_text='Liczba serii.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Serie')),
                ('reps', models.PositiveIntegerField(help_text='Liczba powtórzeń w jednej serii.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Powtórzenia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='training.exercisetype', verbose_name='Rodzaj ćwiczenia')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.trainingsession', verbose_name='Sesja treningowa')),
            ],
        ),
    ]
