# Generated by Django 5.2.8 on 2025-11-30 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['name'], 'verbose_name': 'Typ ćwiczenia', 'verbose_name_plural': 'Typy ćwiczeń'},
        ),
        migrations.AlterModelOptions(
            name='sessionexercise',
            options={'verbose_name': 'Wykonane ćwiczenie', 'verbose_name_plural': 'Wykonane ćwiczenia'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-start'], 'verbose_name': 'Sesja treningowa', 'verbose_name_plural': 'Sesje treningowe'},
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nazwa ćwiczenia'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='training.exercisetype', verbose_name='Typ ćwiczenia'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='reps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Liczba powtórzeń w serii'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='sets',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Liczba serii'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ciężar [kg]'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='end',
            field=models.DateTimeField(verbose_name='Koniec sesji'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start',
            field=models.DateTimeField(verbose_name='Początek sesji'),
        ),
    ]
