# Generated by Django 5.2.8 on 2025-11-30 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_exercisetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sessionexercise',
            options={'ordering': ['-training_session__start']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-start']},
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa ćwiczenia'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Utworzono przez'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='reps',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Powtórzenia'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='sets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utworzono przez'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='end',
            field=models.DateTimeField(verbose_name='Data i czas zakończenia'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start',
            field=models.DateTimeField(verbose_name='Data i czas rozpoczęcia'),
        ),
    ]
